services:
  mysql:
    image: mysql:8.0
    container_name: connex-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: connex_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
